NameSpace: killian
AppName: cuisine-db
NodePort: 32102

MariadbReplicas: 1
MariadbImageTag: latest
MariadbDiskSize: 1Gi
MariadbServerId: 2
MariadbDbName: DB_75j4na2lk
MariadbDbUser: 75j4na2lk
MariadbDbPort: 3306